<?php

return [
    'brand' => [
        'name' => 'MUDEA',
        'logo' => 'images/logo-mudea.png',
        'full_name' => "Mutuelle de Developpement d'Ande",
        'tagline' => 'Notre village, notre force, notre developpement',
        'location' => "Ande, Cote d'Ivoire",
    ],
    'stats' => [
        ['value' => '350+', 'label' => 'membres mobilises'],
        ['value' => '75', 'label' => 'cadres identifies'],
        ['value' => '180', 'label' => 'jeunes accompagnes'],
        ['value' => '120', 'label' => 'membres de la diaspora'],
        ['value' => '12', 'label' => 'projets prioritaires'],
    ],
    'navigation' => [
        ['label' => 'Accueil', 'route' => 'home'],
        ['label' => 'La Mutuelle', 'route' => 'mutuelle'],
        ['label' => 'Gouvernance', 'route' => 'gouvernance'],
        ['label' => 'Vie & Coutumes', 'route' => 'chefferie'],
        ['label' => 'Education', 'route' => 'education'],
        ['label' => 'Espace Communautaire', 'route' => 'solidarite'],
        ['label' => 'Projets', 'route' => 'projets'],
        ['label' => 'Actualites', 'route' => 'actualites'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],
    'footer' => [
        'about' => [
            'title' => 'MUDEA',
            'subtitle' => "Mutuelle de Developpement d'Ande",
            'lines' => [
                'Site frontend simple et clair',
                'Base ideale pour un debutant',
            ],
        ],
        'contact' => [
            'phone' => '+225 01 97 43 00 51',
            'email' => 'contact@mudea-ong.org',
            'location' => "Ande, Cote d'Ivoire",
        ],
        'links' => [
            ['label' => 'Accueil', 'route' => 'home'],
            ['label' => 'La Mutuelle', 'route' => 'mutuelle'],
            ['label' => 'Projets', 'route' => 'projets'],
            ['label' => 'Contact', 'route' => 'contact'],
        ],
        'bottom' => [
            'copyright' => '(c) 2026 MUDEA - Mutuelle de Developpement d\'Ande.',
            'legal' => 'Mentions legales',
            'privacy' => 'Politique de confidentialite',
        ],
    ],
    'pages' => [
        'home' => [
            'title' => 'MUDEA',
            'eyebrow' => 'Portail officiel',
            'subtitle' => "Mutuelle de Developpement d'Ande",
            'slogan' => 'Notre village, notre force, notre developpement',
            'intro' => 'Un frontend simple pour presenter la MUDEA, ses pages institutionnelles, ses projets et ses actualites.',
            'image' => 'hero-village.jpg',
            'mission_line' => 'La plateforme officielle de la MUDEA, claire et accessible sur desktop comme sur mobile.',
            'hero_points' => [
                'Accueil institutionnel',
                'Actualites et projets prioritaires',
                'Education, diaspora et solidarite',
            ],
            'reasons' => [
                [
                    'title' => 'Rassembler',
                    'text' => 'Relier les membres, les jeunes, les cadres, la diaspora et les partenaires.',
                ],
                [
                    'title' => 'Developper',
                    'text' => 'Mettre en avant les initiatives, les projets et les priorites du village.',
                ],
                [
                    'title' => 'Transmettre',
                    'text' => 'Valoriser la memoire, les coutumes et les valeurs de la communaute.',
                ],
            ],
            'project_cards' => [
                [
                    'title' => 'La Mutuelle',
                    'text' => 'Historique, vision, mission, bureau executif et commissions.',
                    'route' => 'mutuelle',
                    'button' => 'Ouvrir la page',
                    'image' => 'community.jpg',
                ],
                [
                    'title' => 'Vie & Coutumes',
                    'text' => 'Histoire du village, patrimoine culturel et memoire locale.',
                    'route' => 'chefferie',
                    'button' => 'Explorer',
                    'image' => 'heritage.jpg',
                ],
                [
                    'title' => 'Education & Excellence',
                    'text' => 'Eleves meritants, etudiants, bourses et programme excellence.',
                    'route' => 'education',
                    'button' => 'Decouvrir',
                    'image' => 'education.jpg',
                ],
                [
                    'title' => 'Espace Communautaire',
                    'text' => 'Place publique, entraide, partage et ressources utiles.',
                    'route' => 'solidarite',
                    'button' => 'Consulter',
                    'image' => 'community.jpg',
                ],
                [
                    'title' => 'Projets',
                    'text' => 'Projets en cours, realises et a venir avec suivi simple.',
                    'route' => 'projets',
                    'button' => 'Voir les projets',
                    'image' => 'hero-village.jpg',
                ],
                [
                    'title' => 'Actualites',
                    'text' => 'Articles, communiques et evenements de la MUDEA.',
                    'route' => 'actualites',
                    'button' => 'Lire les actualites',
                    'image' => 'community.jpg',
                ],
            ],
            'sections' => [
                [
                    'title' => 'Structure simple',
                    'text' => 'Une page d accueil claire avec hero, statistiques, projets et appel a contribution.',
                ],
                [
                    'title' => 'Navigation facile',
                    'text' => 'Chaque rubrique du cahier de charge reste accessible en quelques clics.',
                ],
                [
                    'title' => 'Base pour debutant',
                    'text' => 'Les vues restent petites, reutilisables et faciles a modifier dans Laravel.',
                ],
            ],
        ],
        'mutuelle' => [
            'title' => 'La Mutuelle',
            'eyebrow' => 'A propos',
            'intro' => "Historique, vision, mission, organigramme, bureau executif et commissions de la MUDEA.",
            'image' => 'community.jpg',
            'highlights' => [
                'Historique de creation',
                'Vision et mission',
                'Bureau executif',
                'Commissions de travail',
                'Documents de reference',
            ],
            'sections' => [
                ['title' => 'Historique', 'text' => 'Presenter la naissance de la MUDEA et les grandes etapes de son evolution.'],
                ['title' => 'Vision', 'text' => 'Montrer ce que la mutuelle veut construire pour Ande.'],
                ['title' => 'Organisation', 'text' => 'Afficher les responsables, les commissions et les documents utiles.'],
            ],
        ],
        'gouvernance' => [
            'title' => 'Gouvernance',
            'eyebrow' => 'Organisation',
            'intro' => 'Organisation, fonctionnement, documents officiels, rapports et calendrier des activites.',
            'image' => 'hero-village.jpg',
            'highlights' => [
                'Organisation interne',
                'Fonctionnement',
                'Documents officiels',
                'Rapports et comptes rendus',
                'Calendrier des activites',
            ],
            'sections' => [
                ['title' => 'Clarte', 'text' => 'Une gouvernance lisible aide les membres a comprendre le fonctionnement.'],
                ['title' => 'Documents', 'text' => 'Les statuts et les reglements peuvent etre listes dans cette page.'],
                ['title' => 'Suivi', 'text' => 'Les rapports et le calendrier rendent la vie de la mutuelle plus transparente.'],
            ],
        ],
        'chefferie' => [
            'title' => 'Vie & Coutumes',
            'eyebrow' => 'Patrimoine',
            'intro' => 'Histoire du village, valeurs fondamentales, us et coutumes, patrimoine culturel et galerie.',
            'image' => 'heritage.jpg',
            'highlights' => [
                'Histoire du village',
                'Valeurs traditionnelles',
                'Us et coutumes',
                'Organisation traditionnelle',
                'Patrimoine culturel',
            ],
            'sections' => [
                ['title' => 'Memoire', 'text' => 'Mettre en valeur les origines et les repères du village.'],
                ['title' => 'Culture', 'text' => 'Faire ressortir les coutumes et les traditions locales.'],
                ['title' => 'Galerie', 'text' => 'Une galerie simple peut accueillir photos et archives.'],
            ],
        ],
        'education' => [
            'title' => 'Education et Excellence',
            'eyebrow' => 'Education',
            'intro' => 'Eleves meritants, etudiants, programme excellence, bourses, academie numerique et forum education.',
            'image' => 'education.jpg',
            'highlights' => [
                'Eleves meritants',
                'Etudiants',
                'Programme excellence',
                'Bourses',
                'Academie numerique',
            ],
            'sections' => [
                ['title' => 'Merite', 'text' => 'Mettre en avant les resultats et les parcours inspirants.'],
                ['title' => 'Accompagnement', 'text' => 'Presenter les aides, les bourses et les pistes de mentorat.'],
                ['title' => 'Projection', 'text' => 'Introduire une vision simple pour la formation future.'],
            ],
        ],
        'jeunesse' => [
            'title' => 'Jeunesse',
            'eyebrow' => 'Jeunes',
            'intro' => 'Leadership, initiative, entrepreneuriat, entraide et actions portees par les jeunes.',
            'image' => 'community.jpg',
            'highlights' => [
                'Leadership',
                'Initiatives jeunes',
                'Entrepreneuriat',
                'Entraide',
            ],
            'sections' => [
                ['title' => 'Engagement', 'text' => 'Donner de la place aux jeunes dans la dynamique communautaire.'],
                ['title' => 'Capacitation', 'text' => 'Mettre en avant les formations et les opportunites.'],
                ['title' => 'Action', 'text' => 'Valoriser les projets concrets et les idees utiles.'],
            ],
        ],
        'cadres' => [
            'title' => 'Cadres et Diaspora',
            'eyebrow' => 'Competences',
            'intro' => 'Creer un reseau simple pour les cadres, la diaspora et les competences du village.',
            'image' => 'community.jpg',
            'highlights' => [
                'Repertoire des cadres',
                'Repertoire diaspora',
                'Mentorat',
                'Temoignages',
            ],
            'sections' => [
                ['title' => 'Connexions', 'text' => 'Rapprocher les competences des besoins du village.'],
                ['title' => 'Transmission', 'text' => 'Encourager le mentorat et les retours d experience.'],
                ['title' => 'Mobilisation', 'text' => 'Faciliter les contributions utiles a la communaute.'],
            ],
        ],
        'solidarite' => [
            'title' => 'Espace Communautaire',
            'eyebrow' => 'Place publique',
            'intro' => 'Place publique, ressources et competences, partage d experiences, entraide et solidarite.',
            'image' => 'community.jpg',
            'highlights' => [
                'Place publique',
                'Ressources et competences',
                'Partage d experiences',
                'Entraide et solidarite',
            ],
            'sections' => [
                ['title' => 'Partage', 'text' => 'Un espace pour echanger et s informer facilement.'],
                ['title' => 'Soutien', 'text' => 'Une section simple pour les besoins urgents ou les demandes d aide.'],
                ['title' => 'Ressources', 'text' => 'Une base pour connecter les competences aux besoins locaux.'],
            ],
        ],
        'projets' => [
            'title' => 'Projets',
            'eyebrow' => 'Developpement',
            'intro' => 'Projets en cours, projets realises, projets futurs, etat d avancement et partenaires.',
            'image' => 'hero-village.jpg',
            'highlights' => [
                'Projets en cours',
                'Projets realises',
                'Projets futurs',
                'Etat d avancement',
                'Partenaires',
            ],
            'sections' => [
                ['title' => 'Visibilite', 'text' => 'Chaque projet doit etre simple a lire et a suivre.'],
                ['title' => 'Pilotage', 'text' => 'L etat d avancement rend le suivi plus concret.'],
                ['title' => 'Contribution', 'text' => 'Les visiteurs peuvent comprendre ou intervenir.'],
            ],
        ],
        'transparence' => [
            'title' => 'Transparence',
            'eyebrow' => 'Redevabilite',
            'intro' => 'Rapports d activites, comptes rendus, realisations et informations financieres validees.',
            'image' => 'hero-village.jpg',
            'highlights' => [
                'Rapports d activites',
                'Comptes rendus',
                'Realisations',
                'Informations financieres',
            ],
            'sections' => [
                ['title' => 'Clarte', 'text' => 'Les contenus officiels restent faciles a consulter.'],
                ['title' => 'Confiance', 'text' => 'Une page simple permet de donner des repères fiables.'],
                ['title' => 'Regularite', 'text' => 'La mise a jour doit rester rapide dans la suite du projet.'],
            ],
        ],
        'actualites' => [
            'title' => 'Actualites',
            'eyebrow' => 'Information',
            'intro' => 'Articles, evenements, communiques et informations urgentes de la MUDEA.',
            'image' => 'community.jpg',
            'highlights' => [
                'Articles',
                'Evenements',
                'Communiques',
                'Informations urgentes',
            ],
            'sections' => [
                ['title' => 'Flux vivant', 'text' => 'La rubrique doit donner une impression de site actif.'],
                ['title' => 'Lecture rapide', 'text' => 'Des cartes simples aident a parcourir les contenus.'],
                ['title' => 'Alertes', 'text' => 'Les messages importants peuvent etre mis en avant.'],
            ],
        ],
        'partenaires' => [
            'title' => 'Partenaires',
            'eyebrow' => 'Reseau',
            'intro' => 'Institutions, entreprises, associations, diaspora et sponsors de la MUDEA.',
            'image' => 'hero-village.jpg',
            'highlights' => [
                'Institutions',
                'Entreprises',
                'Associations',
                'Diaspora',
                'Sponsors',
            ],
            'sections' => [
                ['title' => 'Credibilite', 'text' => 'Les partenaires donnent de la force au projet.'],
                ['title' => 'Visibilite', 'text' => 'Les logos et les fiches partenaires peuvent etre presentes ici.'],
                ['title' => 'Ouverture', 'text' => 'La MUDEA montre ainsi sa capacite a travailler avec son ecosysteme.'],
            ],
        ],
        'contact' => [
            'title' => 'Contact',
            'eyebrow' => 'Joindre la MUDEA',
            'intro' => 'Coordonnees, formulaire, reseaux sociaux et localisation de la MUDEA.',
            'image' => 'heritage.jpg',
            'highlights' => [
                'Telephone et email',
                'Formulaire de contact',
                'Reseaux sociaux',
                'Localisation',
            ],
            'sections' => [
                ['title' => 'Rapide', 'text' => 'Le visiteur doit savoir comment joindre la mutuelle sans chercher.'],
                ['title' => 'Clair', 'text' => 'La page peut orienter vers le bon canal selon le besoin.'],
                ['title' => 'Accessible', 'text' => 'Un futur formulaire pourra etre branche tres facilement.'],
            ],
        ],
    ],
];
